### ISSUE TITLE
🎁 [Feature Request]: 4.3 Improve documentation of runtime parameters

### ISSUE THREAD

**Issue by orangelash** [OpenZeppelin/polkadot-generic-runtime-template#143]
### What is the feature you would like to see?

As  runtime  templates  are  meant  to  help  with  bootstrapping  new  developers  to 
accelerated development, it’s critical to reason-about  and  document  hardcoded 
parameters, especially when configuring such parameters has a security relevance. 
This will help developers gain a deeper understanding of the inner  workings of the 
parachain  ecosystem and effectively  navigate  its  complexities  through the  runtime 
template.  For  instance,  SS58Prefix  configuration  in  the  frame_system::Config  is 
hardcoded to  42  [15]. Expanding  on the  rationale  for  the  usage  of  value  42 can  be 
further explained using the ss58-registry [16].  
It is recommended to improve the documentation and inline commenting for all the 
parameters in the runtime template to make the developers aware of the rationale 
behind  the  value.  This  will  also  help  the  developers  in  making  informed  decisions before tweaking the parameters to suit their business logic, thereby improving their 
security posture. 

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by ozgunozerk** [comment]
Elaboration on SS58 value is a good suggestion. 

However, there are just too many constants in the runtime, explaining the rationale behind all of them with inline comments,  will make the code quite unreadable.

Of course, we want the best for the developer. In the end, this template is an effort in order to enhance the dev experience. That's why, we explained nearly all of the constants and config items in our documentation for those who want to learn more. 

I've reviewed all of our constants in the template, and found these potential improvements:
- [ ] SS58 prefix explanation (as suggested)
- [ ] Renaming `MaxScheduledPerBlock` to `MaxScheduledRuntimeCallsPerBlock` for clarity
- [ ] documenting `pallet_treasury` config (it was added later to our runtime, and we probably forgot about its documentation) -> this will be tracked in #150 for the sake of granular issues
